/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.itudoben;

import io.itudoben.log4j2.LogMe1;
import io.itudoben.log4j2.LogMe2;
import io.itudoben.slf4j.SlfLogMe;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

  //    private static final Logger logger = LoggerFactory.getLogger(App.class);
  private static final Logger logger = LogManager.getLogger(App.class);

  private static void say() {
    logger.trace("This is a trace!");
    logger.debug("This is a debug!");
    logger.info("This is an info!");
    logger.warn("This is a warn!");
    logger.error("This is an error!");
  }

  public static void main(String[] args) {
    new LogMeItu().say();
    new LogMe1().say();
    new LogMe2().say();
    new SlfLogMe().say();

    say();
  }
}
